version: '3'
services:
  budgetmanager:
    image: mongo
    container_name: budgetmanager_db
    ports:
      - "27017-27019:27017-27019"
    env_file:
      - database.env
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume: